Controllers/CartController.cs
using MDS_PROJECT.Data;
using MDS_PROJECT.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace MDS_PROJECT.Controllers
{
    public class CartController : Controller
    {
        public class CartViewModel
        {
            public List<CartItem> Items { get; set; } = new List<CartItem>();
            public string CarrefourTotal { get; set; }
            public string KauflandTotal { get; set; }
            public string AuchanTotal { get; set; }
            public string MegaTotal { get; set; }
        }

        public class CartItem
        {
            public string ItemName { get; set; }
            public string Quantity { get; set; }
            public string Unit { get; set; }
            public string CarrefourMessage { get; set; }
            public string KauflandMessage { get; set; }
            public string AuchanMessage { get; set; }
            public string MegaMessage { get; set; }
            public string CarrefourStoreItemName { get; set; }
            public string KauflandStoreItemName { get; set; }
            public string AuchanStoreItemName { get; set; }
            public string MegaStoreItemName { get; set; }
            public int Multiplier { get; set; } = 1;
        }

        public class ItemResult
        {
            public string ItemName { get; set; }
            public string Quantity { get; set; }
            public string MeasureQuantity { get; set; }
            public string Price { get; set; }
            public string Store { get; set; }
            public string Searched { get; set; }
            public int Multiplier { get; set; } = 1;

            public ItemResult() { }

            public ItemResult(Product product)
            {
                ItemName = product.ItemName;
                Quantity = product.Quantity;
                MeasureQuantity = product.MeasureQuantity;
                Price = product.Price;
                Store = product.Store;
                Searched = product.Searched;
            }
        }

        private readonly ApplicationDbContext _db;
        private readonly IConfiguration _configuration;

        public CartController(ApplicationDbContext db, IConfiguration configuration)
        {
            _db = db;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            var viewModel = new CartViewModel();
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Index(List<CartItem> items, bool exactItemName = false)
        {
            var cartViewModel = new CartViewModel { Items = items };
            await CalculateTotals(cartViewModel, items, exactItemName);
            return View(cartViewModel);
        }

        private async Task CalculateTotals(CartViewModel cartViewModel, List<CartItem> items, bool exactItemName)
        {
            decimal carrefourTotal = 0;
            decimal kauflandTotal = 0;
            decimal auchanTotal = 0;
            decimal megaTotal = 0;

            foreach (var item in items)
            {
                Stopwatch stopwatch = Stopwatch.StartNew();
                var existingProducts = _db.Products
                                          .Where(p => p.Searched == item.ItemName)
                                          .ToList();
                stopwatch.Stop();
                Debug.WriteLine($"Database query for {item.ItemName} took {stopwatch.ElapsedMilliseconds} ms");

                var carrefourMessage = "Not found in Carrefour";
                var kauflandMessage = "Not found in Kaufland";
                var auchanMessage = "Not found in Auchan";
                var megaMessage = "Not found in Mega";
                var carrefourStoreItemName = string.Empty;
                var kauflandStoreItemName = string.Empty;
                var auchanStoreItemName = string.Empty;
                var megaStoreItemName = string.Empty;

                if (existingProducts.Any())
                {
                    var carrefourItems = existingProducts.Where(p => p.Store == "Carrefour").Select(p => new ItemResult(p)).ToList();
                    var kauflandItems = existingProducts.Where(p => p.Store == "Kaufland").Select(p => new ItemResult(p)).ToList();
                    var auchanItems = existingProducts.Where(p => p.Store == "Auchan").Select(p => new ItemResult(p)).ToList();
                    var megaItems = existingProducts.Where(p => p.Store == "Mega").Select(p => new ItemResult(p)).ToList();

                    carrefourItems = FilterItems(carrefourItems, item.Quantity);
                    kauflandItems = FilterItems(kauflandItems, item.Quantity);
                    auchanItems = FilterItems(auchanItems, item.Quantity);
                    megaItems = FilterItems(megaItems, item.Quantity);

                    var cheapestCarrefourItem = carrefourItems.OrderBy(p => TryParsePrice(p.Price)).FirstOrDefault();
                    var cheapestKauflandItem = kauflandItems.OrderBy(p => TryParsePrice(p.Price)).FirstOrDefault();
                    var cheapestAuchanItem = auchanItems.OrderBy(p => TryParsePrice(p.Price)).FirstOrDefault();
                    var cheapestMegaItem = megaItems.OrderBy(p => TryParsePrice(p.Price)).FirstOrDefault();

                    if (cheapestCarrefourItem != null)
                    {
                        carrefourTotal += TryParsePrice(cheapestCarrefourItem.Price) * item.Multiplier;
                        carrefourMessage = $"{cheapestCarrefourItem.ItemName}: {cheapestCarrefourItem.Price} Lei";
                        carrefourStoreItemName = cheapestCarrefourItem.ItemName;
                    }

                    if (cheapestKauflandItem != null)
                    {
                        kauflandTotal += TryParsePrice(cheapestKauflandItem.Price) * item.Multiplier;
                        kauflandMessage = $"{cheapestKauflandItem.ItemName}: {cheapestKauflandItem.Price} Lei";
                        kauflandStoreItemName = cheapestKauflandItem.ItemName;
                    }

                    if (cheapestAuchanItem != null)
                    {
                        auchanTotal += TryParsePrice(cheapestAuchanItem.Price) * item.Multiplier;
                        auchanMessage = $"{cheapestAuchanItem.ItemName}: {cheapestAuchanItem.Price} Lei";
                        auchanStoreItemName = cheapestAuchanItem.ItemName;
                    }

                    if (cheapestMegaItem != null)
                    {
                        megaTotal += TryParsePrice(cheapestMegaItem.Price) * item.Multiplier;
                        megaMessage = $"{cheapestMegaItem.ItemName}: {cheapestMegaItem.Price} Lei";
                        megaStoreItemName = cheapestMegaItem.ItemName;
                    }
                }
                else
                {
                    var carrefourTask = GetSearchResult("Carrefour.py", item.ItemName, exactItemName);
                    var kauflandTask = GetSearchResult("Kaufland.py", item.ItemName, exactItemName);
                    var auchanTask = GetSearchResult("Auchan.py", item.ItemName, exactItemName);
                    var megaTask = GetSearchResult("Mega.py", item.ItemName, exactItemName);

                    await Task.WhenAll(carrefourTask, kauflandTask, auchanTask, megaTask);

                    var carrefourResults = ParseResults(carrefourTask.Result, "Carrefour");
                    var kauflandResults = ParseResults(kauflandTask.Result, "Kaufland");
                    var auchanResults = ParseAuchanResults(auchanTask.Result);
                    var megaResults = ParseMegaResults(megaTask.Result);

                    carrefourResults = FilterItems(carrefourResults, item.Quantity);
                    kauflandResults = FilterItems(kauflandResults, item.Quantity);
                    auchanResults = FilterItems(auchanResults, item.Quantity);
                    megaResults = FilterItems(megaResults, item.Quantity);

                    var cheapestCarrefourItem = carrefourResults.OrderBy(p => TryParsePrice(p.Price)).FirstOrDefault();
                    var cheapestKauflandItem = kauflandResults.OrderBy(p => TryParsePrice(p.Price)).FirstOrDefault();
                    var cheapestAuchanItem = auchanResults.OrderBy(p => TryParsePrice(p.Price)).FirstOrDefault();
                    var cheapestMegaItem = megaResults.OrderBy(p => TryParsePrice(p.Price)).FirstOrDefault();

                    if (cheapestCarrefourItem != null)
                    {
                        carrefourTotal += TryParsePrice(cheapestCarrefourItem.Price) * item.Multiplier;
                        carrefourMessage = $"{cheapestCarrefourItem.ItemName}: {cheapestCarrefourItem.Price} Lei";
                        carrefourStoreItemName = cheapestCarrefourItem.ItemName;
                        SaveProductToDatabase(cheapestCarrefourItem, item.ItemName);
                    }

                    if (cheapestKauflandItem != null)
                    {
                        kauflandTotal += TryParsePrice(cheapestKauflandItem.Price) * item.Multiplier;
                        kauflandMessage = $"{cheapestKauflandItem.ItemName}: {cheapestKauflandItem.Price} Lei";
                        kauflandStoreItemName = cheapestKauflandItem.ItemName;
                        SaveProductToDatabase(cheapestKauflandItem, item.ItemName);
                    }

                    if (cheapestAuchanItem != null)
                    {
                        auchanTotal += TryParsePrice(cheapestAuchanItem.Price) * item.Multiplier;
                        auchanMessage = $"{cheapestAuchanItem.ItemName}: {cheapestAuchanItem.Price} Lei";
                        auchanStoreItemName = cheapestAuchanItem.ItemName;

Controllers/MapsController.cs
using Microsoft.AspNetCore.Mvc;

namespace MDS_PROJECT.Controllers
{
    public class MapsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MDS_PROJECT</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/mycss.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MDS_PROJECT.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @* <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Maps" asp-action="Index">Map</a>

                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>